### ISSUE TITLE
PHP function get_magic_quotes_gpc deprecated/removed

### ISSUE THREAD

**Issue by bwenrich** [koalaman/shellcheck.net#16]
Noticed that the shellcheck.php script is incompatible with PHP8. The PHP function get_magic_quotes_gpc() was deprecated in PHP 5.4 and removed in PHP 8.0.

https://www.php.net/manual/en/function.get-magic-quotes-gpc.php
https://stackoverflow.com/questions/61054418/php-7-4-deprecated-get-magic-quotes-gpc-function-alternative/61260285

Staring with PHP 5.4, the function was changed to always return False, so the condition here can never execute.
```
$script = $_POST["script"];
if (get_magic_quotes_gpc()) {
    $script = stripslashes($script);
}
```

Wondering if stripslashes() is also irrelevant due to PHP changes after 5.x, or some other logic is needed to decide when to use stripslashes(). I run a demo site based on shellcheck.net and currently testing upgrade from PHP 7.4 -> PHP 8.x

**Comment by koalaman** [comment]
Thanks for keeping it up to date!
