### ISSUE TITLE
Expired TLS certificate on shellcheck.net

### ISSUE THREAD

**Issue by 357up** [koalaman/shellcheck.net#23]
Let's Encrypt certificate for shellcheck.net and www.shellcheck.net expired on the 18th of September, 2022.
![Screenshot from 2022-09-19 11-02-33](https://user-images.githubusercontent.com/19869011/190974240-a98537ba-8dfb-472c-9e8e-a84e2dc45fe7.png)

**Comment by koalaman** [comment]
Fixed, thanks

**Comment by dak180** [comment]
@koalaman same thing again, cert expired 1 day ago.

**Comment by koalaman** [comment]
Fixed again, thanks
