### ISSUE TITLE
Certificate expired?

### ISSUE THREAD

**Issue by bewuethr** [koalaman/shellcheck.net#32]
shellcheck.net shows me this currently:

![image](https://github.com/koalaman/shellcheck.net/assets/8521043/871cf798-4e41-46f5-baa3-80e665c518ab)

**Comment by koalaman** [comment]
Letsencrypt decided to write the updated keys to a new directory for some reason. It's fixed now. Thanks!

**Comment by jonathan-conder** [comment]
@koalaman looks like the cert has expired again
