### ISSUE TITLE
Site appears to be down

### ISSUE THREAD

**Issue by aphedges** [koalaman/shellcheck.net#35]
I cannot access <https://www.shellcheck.net/>, and <https://downforeveryoneorjustme.com/shellcheck.net?proto=https&www=1> indicates that the problem is not just me.

**Comment by aphedges** [comment]
I don't know what the problem was, but the site is back up now. I'll close this issue for now and re-open it if there are problems again.

**Comment by koalaman** [comment]
The host ran out of disk space :P

**Comment by aphedges** [comment]
Good to know. Thanks for fixing it!
