### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by 3noch** [koalaman/shellcheck.net#4]
@koalaman I have some ideas on how to improve this site. If you're willing, I'd love to talk to you in person about making some contributions. I am part owner in an up-and-coming marketing company that uses Haskell for as much as possible (http://www.graftedindesign.com). That's not a common combination. I think we could make some marketing-oriented contributions that you would like. I don't really want to sell you anything. I really believe in Haskell and I think ShellCheck is an utterly amazing tool. I want to see it get more exposure since most people I meet have never heard of it! Respond to this or email me (see my profile) if you'd like to talk it over.

**Comment by koalaman** [comment]
What do you have in mind?

**Comment by 3noch** [comment]
We have several ideas, including a new visual design for the site with better SEO optimization and pushing more content (like articles, best practices, use cases, editor plugins, etc.). We'd even like to start promoting ShellCheck on other sites. Some of that costs money which could easily be funded by putting highly-relevant ads on the site (developer-oriented ads for editors, Haskell, etc.). Not to toot my own horn but we're experts in this kind of thing and would love to donate our time to these improvements. Our benefit would come in the form of better public exposure.

**Comment by koalaman** [comment]
I don't think I'm in your target market. I'm not really interested in ads or ad revenue and I'm not looking for a second job running a developer portal.

Pull requests are always considered, but I think there are many other sites in need of contributions that are better able to appreciate what you do.

**Comment by 3noch** [comment]
Fair enough. In all honesty I was hoping not to add any burden to you as I'd be the one doing most of the work. I realize you likely have plenty to do already. I appreciate the chance to talk it over though. And thank you for an absolutely amazing tool.

**Comment by 3noch** [comment]
If you don't mind, I'll probably end posting content about ShellCheck around the web and trying to give it some exposure that way. I'm baffled at how few people use it, relatively speaking.

**Comment by koalaman** [comment]
I'm glad you find it useful! Feel free to post about it.

If you have any patches or suggestions for the web site that don't involve actively managing it, do let me know.

**Comment by 3noch** [comment]
Will do. Thank you.
